### ISSUE TITLE
'executor is null or undefined' error on Mobile Safari

### ISSUE THREAD

**Issue by klamping** [applitools/eyes.webdriverio.javascript#15]
When trying to run `checkWindow` in Mobile Safari, I'm getting the following error:
```
IllegalArgument: executor is null or undefined
running Safari
Error: IllegalArgument: executor is null or undefined
    at Function.notNull (/Users/klamping/Sites/reserve/qa/node_modules/@applitools/eyes.sdk.core/lib/ArgumentGuard.js:45:13)
    at new CssTranslatePositionProvider (/Users/klamping/Sites/reserve/qa/node_modules/@applitools/eyes.webdriverio/lib/positioning/CssTranslatePositionProvider.js:21:19)
    at Eyes._initPositionProvider (/Users/klamping/Sites/reserve/qa/node_modules/@applitools/eyes.webdriverio/lib/Eyes.js:774:34)
    at Eyes.setStitchMode (/Users/klamping/Sites/reserve/qa/node_modules/@applitools/eyes.webdriverio/lib/Eyes.js:1237:12)
```

My capabilities:
```
{
  browserName: 'Safari',
  deviceName: 'iPhone X Simulator',
  deviceOrientation: 'portrait',
  platformVersion: '11.2',
  platformName: 'iOS',
  locationContextEnabled: true,
  nativeEvents: true,
  handlesAlerts: true,
}
```

**Comment by danielputerman** [comment]
Fixed in https://github.com/applitools/eyes.webdriverio.javascript/pull/14, and available in npm since version 1.1.1.
