### ISSUE TITLE
'versionMatch.group is not a function' error in Safari

### ISSUE THREAD

**Issue by klamping** [applitools/eyes.webdriverio.javascript#17]
When trying to run the `eyes.open` command in Safari, I get the following error message:

```
versionMatch.group is not a function
running safari
TypeError: versionMatch.group is not a function
    at Function.parseUserAgentString (/Users/klamping/Sites/test-app-wdio/node_modules/@applitools/eyes.sdk.core/lib/utils/UserAgent.js:178:50)
    at Eyes.open (/Users/klamping/Sites/test-app-wdio/node_modules/@applitools/eyes.webdriverio/lib/Eyes.js:138:35)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

This does not occur in Firefox or Chrome in OS X. 

You can recreate this issue using this repo:
https://github.com/klamping/test-app-wdio/

**Comment by danielputerman** [comment]
Fixed a while ago, sorry for the delayed update :)
