### ISSUE TITLE
unable to use applitools with webdriverio in mobile native app

### ISSUE THREAD

**Issue by LayMuiToh** [applitools/eyes.webdriverio.javascript#42]
wdio.conf.js:
```
services: ['appium', 'selenium-standalone',
    'eyes.selenium'],


 //applitoolsKey: '3xTFh8pyaJr2TEgwPnOb55f7QeF5iPejd0pmBAppl108c110',
    applitools: {
        apiKey : '3xTFh8pyaJr2TEgwPnOb55f7QeF5iPejd0pmBAppl108c110',
        appName: "Eaton App",                  //Recommended
       // viewport: {}      , //Recommended for web, don't use in mobile
      //  batchName: "Config Batch",                  //Optional
      //  globalMatchLevel: "Strict",                 //Optional
      //  disableCSSScrolling: false,                 //Optional
      //  disableFullPageScreenshot: false,           //Optional
      //  serverUrl: "https://eyes.applitools.com"    //Optional
    },
```
```
code snippet:
describe('Options test', () => {
   
    it('should able to select sales icon and go to the Sales page', () => {
       // Start the test.
      browser.eyesOpen("Main");
      Main.sales.waitForVisible() && 
      Main.sales.click(); 
      
      browser.eyesCheckWindow("Sales Page");
```

```
"devDependencies": {
    "@applitools/eyes.webdriverio": "^2.0.0",
    "@wdio/applitools-service": "^5.0.0",
    "@wdio/eyes.webdriverio": "^2.0.3",
    "babel-cli": "^6.26.0",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2015-node": "^6.1.1",
    "babel-preset-react-native": "^4.0.1",
    "babel-preset-stage-2": "^6.24.1",
    "babel-register": "^6.26.0",
    "babel-runtime": "^6.26.0",
    "eyes.selenium": "^3.6.2",
    "node-wav-player": "^0.1.0",
    "wdio-appium-service": "^0.2.3",
    "wdio-applitools-service": "^0.2.2",
    "wdio-eyes.selenium-service": "0.0.15",
    "wdio-selenium-standalone-service": "0.0.10",
    "wdio-mocha-framework": "^0.6.4",
    "wdio-screenshot": "^0.6.0",
    "wdio-sync": "^0.7.3",
    "webdriverio": "^4.14.1"
  },
```

```
error seen:
1) Options test should able to select sales icon and go to the Sales page:
Method is not implemented
running
WebDriverError: Method is not implemented
    at Object.checkLegacyResponse (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/error.js:546:15)
    at parseHttpResponse (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/http.js:509:13)
    at doSend.then.response (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/http.js:441:30)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
From: Task: WebDriver.executeScript()
    at WebDriver.schedule (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
    at WebDriver.executeScript (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/webdriver.js:878:16)
    at EyesWebDriver.getUserAgent (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/eyes.selenium/src/EyesWebDriver.js:76:29)
    at /Users/tohlaymui/Desktop/performance_analyst_test/node_modules/eyes.selenium/src/Eyes.js:171:33
    at ManagedPromise.invokeCallback_ (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (/Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at /Users/tohlaymui/Desktop/performance_analyst_test/node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>

2) Options test should able to go back to Main Page:
checkWindow called with Eyes not open
running
Error: checkWindow called with Eyes not open
    at Eyes.<anonymous> (node_modules/eyes.sdk/src/EyesBase.js:1283:23)
    at new Promise (<anonymous>)
    at node_modules/eyes.selenium/src/Eyes.js:77:24
    at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2974:25)
    at node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
    From: Task: <anonymous>
    at PromiseFactory.that._promiseFactory.setFactoryMethods.defer [as _promiseFactoryFunc] (node_modules/eyes.selenium/src/Eyes.js:76:25)
    at PromiseFactory.makePromise (node_modules/eyes.utils/src/PromiseFactory.js:38:25)
    at EyesBase.checkWindow (node_modules/eyes.sdk/src/EyesBase.js:1272:37)
    at node_modules/eyes.selenium/src/Eyes.js:343:51
    at ManagedPromise.invokeCallback_ (node_modules/selenium-webdriver/lib/promise.js:1376:14)
    at TaskQueue.execute_ (node_modules/selenium-webdriver/lib/promise.js:3084:14)
    at TaskQueue.executeNext_ (node_modules/selenium-webdriver/lib/promise.js:3067:27)
    at asyncRun (node_modules/selenium-webdriver/lib/promise.js:2927:27)
    at node_modules/selenium-webdriver/lib/promise.js:668:7
    at <anonymous>

```

**Comment by yuriieasternpeak** [comment]
@LayMuiToh , can you share your test project?
