### ISSUE TITLE
Failed to set/get viewport size: TypeError: actualViewportSize.equals is not a function

### ISSUE THREAD

**Issue by kobenguyent** [applitools/eyes.webdriverio.javascript#74]
I got the following error when trying to set the height is greater than 754.
```js
await eyes.open(client, appName, suite.title, {'width': 1920, 'height': 755});
```

```js
Failed to set/get viewport size: TypeError: actualViewportSize.equals is not a function
  estFailedError: TypeError: actualViewportSize.equals is not a function
      at /Users/thanhnguyen/Desktop/test/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:815:17
      at processTicksAndRejections (internal/process/task_queues.js:89:5)
      at async Eyes.open (node_modules/@wdio/eyes.webdriverio/src/Eyes.js:164:5)
```

**Comment by yuriieasternpeak** [comment]
> I got the following error when trying to set the height is greater than 754.
> 
> ```js
> await eyes.open(client, appName, suite.title, {'width': 1920, 'height': 755});
> ```
> 
> ```js
> Failed to set/get viewport size: TypeError: actualViewportSize.equals is not a function
>   estFailedError: TypeError: actualViewportSize.equals is not a function
>       at /Users/thanhnguyen/Desktop/test/node_modules/@wdio/eyes.webdriverio/src/Eyes.js:815:17
>       at processTicksAndRejections (internal/process/task_queues.js:89:5)
>       at async Eyes.open (node_modules/@wdio/eyes.webdriverio/src/Eyes.js:164:5)
> ```

Can you share your test and package.json?

**Comment by kobenguyent** [comment]
@yuriieasternpeak I tried the tests from here https://github.com/PeterNgTr/applitools-example.

here is the `package.json`
https://github.com/PeterNgTr/applitools-example/blob/master/package.json
